spring:
  application:
    name: spring-rabbitmq

  threads.virtual.enabled: true
  jackson.property-naming-strategy: SNAKE_CASE

  rabbitmq:
    host: localhost
    port: 5672
    username: spring-rabbitmq
    password: spring-rabbitmq
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
      observation-enabled: true
      retry:
        enabled: true
        initial-interval: 1s
        max-interval: 10s
        multiplier: 2
        max-retries: 3
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
        prefetch: 50
        concurrency: 3
        max-concurrency: 10
        observation-enabled: true
        retry:
          enabled: true
          initial-interval: 2s
          max-attempts: 4
          multiplier: 2

  datasource:
    url: jdbc:postgresql://localhost:5432/spring-rabbitmq
    username: spring-rabbitmq
    password: spring-rabbitmq

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

rabbitmq:
  queues:
    emails:
      name: emails
      concurrency: 10-50
